[package]
name = "simply-kaspa-acceptance-tool"
description = "Simply Kaspa Indexer"
rust-version.workspace = true
authors.workspace = true
license-file.workspace = true
edition.workspace = true

[features]
default = []

[dependencies]
simply-kaspa-acceptance-tool-cli.workspace = true
simply-kaspa-acceptance-tool-kaspad.workspace = true
simply-kaspa-acceptance-tool-database.workspace = true
kaspa-wrpc-client.workspace = true
kaspa-rpc-core.workspace = true
kaspa-hashes.workspace = true
tokio.workspace = true
deadpool.workspace = true
futures-util.workspace = true
crossbeam-queue.workspace = true
chrono.workspace = true
bigdecimal.workspace = true
hex.workspace = true
env_logger.workspace = true
log.workspace = true
clap.workspace = true
serde.workspace = true
serde_with.workspace = true
serde_json.workspace = true
